### ISSUE TITLE
Cloud sql instance should not crash if it already exists.

### ISSUE THREAD

**Issue by enriquejosepadilla** [GoogleCloudPlatform/django-cloud-deploy#110] opened 2018-11-29 21:12 UTC
We should make a check if it exists to use it and not crash the program.

**Comment by brianquinlan** [comment] 2018-12-15 00:59
Is this fixed?

**Comment by wangxf123456** [comment] 2018-12-17 18:20
Not yet.

**Comment by wangxf123456** [comment] 2019-02-05 21:48
Duplicate of #210

**Comment by wangxf123456** [comment] 2019-02-15 23:38
Fixed in #221

**Closed by wangxf123456** 2019-02-15 23:38 UTC
Labels: user study
